### ISSUE TITLE
Unable to run this

### ISSUE THREAD

**Issue by apperrault** [feederbox826/stash-backup#1]
Hey there
i'm hoping I'm missing something small.  I am trying to get this running on my docker infrastructure.  This is what I have in my docker-config.yml and the .env I only updated the address and API key

```
services:
  stash-backup:
    image: ghcr.io/feederbox826/stash-backup:latest
    container_name: stash-backup
    volumes:
     - ${DOCKERCONFDIR}/stash-backup:/app/backup
    env_file:
      - .env
    environment:
     - STASH_URL=http://192.168.0.20:9999
     - STASH_APIKEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     - CRON_SCHEDULE=*/10 * * * * # every 10 minutes
     - DISCORD_WEBHOOK="https://discord.com/api/webhooks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
     - NOTIFY_ENABLED=true
     - DIFF_CRON=0 0 * * * # every day
     - FULL_CRON=0 0 */7 * * # every 7 days
     - CONSOLIDATE_CRON=0 0 2 * * # second of every month
     - IMG_CRON=0 0 1 * * # first of every month
```

When I run compose with this info I get this message
```
stash-backup  | jq: parse error: Invalid numeric literal at line 1, column 10
stash-backup  | No such file or directory
stash-backup  | mv: cannot stat '': No such file or directory
```

i'm also on the Stash Discord if you want to hit me up there

aaron
